config/routes.rb
Rails.application.routes.draw do

  root 'puzzles#index'

  post '/ScoreCreate', to: 'scores#create'

  resources :puzzles, only: [:index, :show]
  resources :characters, only: [:index]
  resources :scores, only: [:create]

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/character.rb
class Character < ApplicationRecord
  belongs_to :puzzle
end

app/models/puzzle.rb
class Puzzle < ApplicationRecord
  has_many :characters
  has_many :scores
end

app/models/score.rb
class Score < ApplicationRecord
  belongs_to :puzzle
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/characters_controller.rb
class CharactersController < ApplicationController
  def index
    @characters = Character.all
    respond_to do |format|
      # remove the updated_at, id, and created_at attributes from the results.
      format.json { render json: @characters, except: [:id, :created_at, :updated_at] }
    end
  end
end

app/controllers/puzzles_controller.rb
class PuzzlesController < ApplicationController
  def index
    @puzzles = Puzzle.all
  end

  def show
    @puzzle = Puzzle.find(params[:id])
    @scores = @puzzle.scores.order(number: :asc).limit(10)
  end
end

app/controllers/scores_controller.rb
class ScoresController < ApplicationController
  def index
    @scores = Score.all
  end

  def create
    @score = Score.new(score_params)
    @score.save
  end

  private

  def score_params
    params.permit(:number, :player_name, :puzzle_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/characters_helper.rb
module CharactersHelper
end

app/helpers/puzzles_helper.rb
module PuzzlesHelper
end

app/helpers/scores_helper.rb
module ScoresHelper
end

app/views/characters/index.html.erb
<h1>Characters#index</h1>
<p>Find me in app/views/characters/index.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>OdinWheresWaldo</title>

    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <header class="header">
      <nav class="nav">
        <ul>
          <li class="nav__item">
            <%= link_to "OdinWheresWaldo", "/", class: "nav__link" %>
          </li> 
        </ul>
      </nav> 
    </header>

    <main class="main">
      <%= yield %>
    </main>

    <footer class="footer">
      <span class="footer__text">
        Copyright &copy; 2019 Ben Garcia
      </span>
      <a class="footer__link" href="https://github.com/ben-garcia/odin_wheres_waldo/">
        View Code
      </a>
    </footer>

  </body>

</html>

app/views/puzzles/index.html.erb
<h1 class="title">Where's Waldo?</h1>

<section class="puzzles">
  <ul class="puzzles__items">
    <% # to display the puzzles in the proper order based on difficulty %>
    <% @puzzles = [@puzzles[0], @puzzles[2], @puzzles[1]] %>
    <% @puzzles.each do |puzzle| %>
      <li>
        <article class="puzzle__item">
          <img
            class="puzzle__img"
            src="<%= puzzle.url %>"
            alt="<%= puzzle.difficulty %> puzzle"
          />
          <div class="puzzle__info">
            <h2 class="puzzle__title"><%= puzzle.title %></h2> 
            <p class="puzzle__difficulty">Difficulty: <%= puzzle.difficulty %></p>
            <button class="info__button" id="<%= puzzle.title %>" type="button">Play</button>
            <%= link_to "High Scores", puzzle_path(puzzle), class: "info__button" %>
          </div>
        </article>
      </li>
    <% end %>
  </ul>
</section>

app/views/puzzles/show.html.erb
<section class="scores"> 
  <h1 class="title">High Scores for <%= @puzzle.title %></h1>
  <table class="table">
    <thead class="table__head">
      <tr>
        <th class="table__column"></th>
        <th class="table__column">Name</th>
        <th class="table__column">Score</th>
      </tr>
    </thead>
    <tbody class="table__body">
      <% @scores.each_with_index do |score, index| %>
        <tr class="table__row">
          <td><%= index + 1 %></td>
          <td><%= score.player_name %></td>

          <% if score.number.to_s.size == 6 %>
              <% number_string = score.number.to_s %>
              <% minutes = number_string[0] + number_string[1] %>
              <% seconds = number_string[2] + number_string[3] + "." + number_string[4] + number_string[5] %>

              <td><%= minutes + "m " + seconds + "s" %></td>
          <% elsif score.number.to_s.size == 5 %>
            <% number_string = score.number.to_s %>
            <% minutes = number_string[0] %>
            <% seconds = number_string[1] + number_string[2] + "." + number_string[3] + number_string[4] %>

            <td><%= minutes + "m " + seconds + "s" %></td>
          <% elsif score.number.to_s.size == 4 %>
            <% number_string = score.number.to_s %>
            <% seconds = number_string[0] + number_string[1] + "." + number_string[2] + number_string[3] %>

            <td><%= seconds + "s" %></td>
          <% elsif score.number.to_s.size == 3 %>
            <% number_string = score.number.to_s %>
            <% seconds = number_string[0] + "." + number_string[1] + number_string[2] %>

            <td><%= seconds + "s" %></td>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>
</section>